### PR TITLE
Interactive interpreter improved.

### PR DESCRIPTION
**Pull request by abeutot**
Using readline if available.
Using a custom code.InteractiveConsole on the injected process side.

### CODE REVIEW

**Comment by lmacken** [comment]
First off, thank you for the patch! I was unable to figure out how to do this to begin with; I didn't even know the code module existed until now :)

However, for some reason, I'm unable to get the basic example of modifying a variable in another interpreter working with the new shell. http://pyrasite.readthedocs.org/en/latest/Shell.html -- does it work for you?

**Comment by lmacken** [comment]
Ah, I think I figured it out. Will merge and fix.

**Comment by lmacken** [comment]
Ok, I think I solved the problem by passing the globals into the console (98e9564a4da09ff7006f77bc7d5ca08ff07e2d49)

Thanks again for the patch!

**Comment by abeutot** [comment]
Yes, I'm sorry, I just figured out after I made the pull request that I forgot the globals(), I was going to make an other one. Glad you found it.

Thanks.

**Pull request merged**
